/* Auto-generated by builder.py - DO NOT EDIT */
#ifndef CONFIG_H
#define CONFIG_H

/* Server IP: 127.0.0.1 */
#define SERVER_IP_OCTET_0 127
#define SERVER_IP_OCTET_1 0
#define SERVER_IP_OCTET_2 0
#define SERVER_IP_OCTET_3 1

/* Server Port: 4444 (network byte order: 0x115c) */
#define SERVER_PORT 4444
#define SERVER_PORT_NBO htons(SERVER_PORT)

/* Authentication password */
#define AUTH_PASSWORD_LEN 4
#define AUTH_PASSWORD { 0xde, 0xad, 0xbe, 0xef }

/* Server read timeout for authentication (seconds) */
#define AUTH_TIMEOUT_SEC 2

#endif /* CONFIG_H */
